### ISSUE TITLE
是否把爬虫的max_level设置读取config比较好？

### ISSUE THREAD

**Issue by endingman** [wi1dcard/china-divisions#3]
读取config灵活一些，可以根据项目需要爬数据。比如有些项目需要5级的，爬虫源码最大4级。

**Comment by wi1dcard** [comment]
嗯，爬虫是随手写的一个脚本，按理说读参数比较合适，偷懒就直接写成常量了。等有时间的时候修改一下，感谢关注。

**Comment by endingman** [comment]
好。
