### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '?'

### ISSUE THREAD

**Issue by chpiter** [wi1dcard/china-divisions#4]
PHP Parse error:  syntax error, unexpected '?' in /data/china-divisions/scripts/crawler.php on line 13

function division_filter(array $data) : ?array

**Comment by chpiter** [comment]
PHP 7.0.33 (cli) (built: Dec  6 2018 22:30:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

请问下，我的PHP版本低吗？

**Comment by chpiter** [comment]
好了，升级到7.2可以了
查了下文档，是从7.1开始支持的特性

**Comment by wi1dcard** [comment]
感谢关注，此处应当声明 PHP 版本须 `^7.1`，将会在后续改进。

**Comment by wi1dcard** [comment]
暂时先不要关闭这个 Issue，等后续修复后再关闭。
