### ISSUE TITLE
菜鸟的数据好像更新也不是很及时

### ISSUE THREAD

**Issue by youcanping** [wi1dcard/china-divisions#6]
还是 http://www.mca.gov.cn/article/sj/xzqh/2019/ 中国行政区域查询的比较及时

**Comment by wi1dcard** [comment]
可以举例吗？

**Comment by daifee** [comment]
@wi1dcard 请教个问题。这些数据会变更，不需要版本号区分吗？

**Comment by wi1dcard** [comment]
Hi @daifee，请问你提到的「数据变更」是指什么？

**Comment by daifee** [comment]
@wi1dcard 政府会变更某些地区的区号、名称，新旧code, id可能会存在冲突。 如果所有变更都是新增code、id，则不需要版本。

**Comment by wi1dcard** [comment]
@daifee 变更不会将某个地区的 Code 重新分配给另一个地区，而是会标记为已废弃并新增一个地区。

**Comment by daifee** [comment]
@wi1dcard 理解了。谢谢
